### ISSUE TITLE
Sign & Connect

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#13]
Is this the same thing? Do we need them both?

**Comment by loogart** [comment]
@naeemadam connect is a dropdown which shows social media channels, sign in is where the user logs in to vote. Would you rather i change the name of "Connect" to "social media" (or something to that effect)?

**Comment by naeemadam** [comment]
@loogart but do they do the samething? Is connect Like our social channels so people can like us or sign in using their personal?

**Comment by loogart** [comment]
@naeemadam oh i see what you mean. Connect is simply the links to the BW social channels. Sign in is essentially logging on with your personal FB. I can change "Connect" --> "More" and include the social channels, about, FAQ and anything else you want to add in the future.

**Comment by loogart** [comment]
@naeemadam to simplify things, I called the dropdown "MORE" instead of "Connect" to avoid any confusion. In this dropdown, the user will have access to social media, about and any additional page that is secondary.

![screen shot 2017-06-30 at 2 45 11 pm](https://user-images.githubusercontent.com/7881400/27749787-014e509e-5da3-11e7-88e4-6cbc049160ae.png)

**Comment by naeemadam** [comment]
Looks fantastic. Ill make updates to the copy in the html file.
